### PR TITLE
Don't auto add packages if they cause conflicts; Prompt for conflicts BEFORE adding a package

### LINKED ISSUE #441: Removing conflicting packages results in the possibility of stray blocks
If we try to add the bluetooth package, when radio is installed, we are prompted with the need to remove one of them. 
If we have existing radio blocks and remove the radio package. We're left with blocks that don't work, and don't compile to typescript. 
Refreshing the page is also an issue, as it results in black unknown blocks (that look like a bug to the user). 
image

Maybe we should remove related blocks when removing a (conflicting) package.

### LINKED ISSUE #905: Addition of incompatible libraries gives non-intuitive/not-expected dialog "suggestion"
In connection with addition of an incompatible library to a project, the requester has a suggestion that the correct answer is remove the library one has requested be added.

"Suggestion" is that the library to be added has a greater weight than the library that would be needed to be removed.
image

### LINKED ISSUE #1119: Incompatible packages warning is unhelpful and recurring when blocks from a package are already used
Using pxt.microbit.org/beta I see the following issue:

Add some blocks that use radio to a program
try to add the bluetooth package
You get the following dialogue
image
Choosing 'Remove Radio' doesn't work, it just respawns the dialogue. Choosing 'Remove Bluetooth' ends the respawn loop but doesn't help the user understand the problem
remove radio

Instead I think it would be better to explain to the user after the first 'Remove Radio' that this cannot be done because there are radio blocks in the program. The user can then remove them and try again
(This works fine if there are no radio/bluetooth blocks already there)

Also the little message that mentions yotta settings being incompatible seems a bit too much detail? It is only there a little while, though..

### LINKED ISSUE #1159: Incompatible packages dialog is unclear about repercussions
Its unclear from the incompatible packages dialog text that you'll lose any references to radio. I think it needs to be clear that if you are using any radio blocks / references you will lose those by removing 'Radio'. 

screen shot 2017-01-17 at 9 40 46 am

Otherwise you can find yourself with empty blocks, not knowing why.

### LINKED ISSUE #1232: Add Package Feature does not allow Blue Tooth to be substituted by Radio
microbit.org-ticket: 815

When trying the "Add Package" Feature I had Radio on the primary list and asked for Blue Tooth. I was told that either Blue Tooth of Radio had to be removed. I selected Blue Tooth but this would not be accepted and the Remove window came up again.  The only way I could get out of this loop was to accept Blue Tooth.  

I then tried to "Add Package" - Radio but as before, this was not allowed.  In fact the Remove Blue Tooth option is a lighter colour as though it had been greyed out.  

I signed out and back in, using microbit org  PTX but got a conflict message that was too fast to record but was along the lines   " Conflict on yotta settings microbit.bluetooth enabled etc ...."

The screen I was left with was mostly blank and unusable except I tried Getting Started which gives me the getting started editor which may work.

### LINKED ISSUE #1236: yotta conflict on aborted add package
yottaconflict

### PR DESCRIPTION
**Pull request by guillaumejenkins**
Fixes #441
Fixes #905
Fixes #1119
Fixes #1159
Fixes #1232
Fixes #1236

### CODE REVIEW

**Comment by pelikhan** [comment]
Could we try to get some test cases for this logic? It's getting quite intricate.

File: webapp/src/app.tsx [hunk 1]
```diff
@@ -260,14 +258,71 @@ class ScriptSearch extends data.Component<ISettingsProps, ScriptSearchState> {
...
+                                return false;
+                            });
+                    } else if (conflicts.length) {
+                        const conflictNames = conflicts.map((c) => c.pkg0.id).join(",<br/>");
+                        addDependencyPromise = addDependencyPromise
+                            .then(() => core.confirmAsync({
+                                header: lf("Packages will be removed"),
+                                agreeLbl: lf("Remove packages and add {0}", config.name),
+                                agreeClass: "pink",
+                                htmlBody: `<p>${lf("The following package(s) are incompatible with {0} and will be removed. Continue?", config.name, conflictNames)}<br/><br/>${conflictNames}`
```
Comment (pelikhan) [inline webapp/src/app.tsx]: Use "body" or escape all user provided strings.

File: pxtlib/main.ts [hunk 2]
```diff
@@ -189,15 +189,33 @@ namespace pxt {
     }
 
     export class Package {
+        static getConfigAsync(id: string, fullVers: string): Promise<pxt.PackageConfig> {
+            const ghConfig = /^github:(.*)#(.*)$/.exec(fullVers);
+            return Promise.resolve().then(() => {
+                if (ghConfig) {
+                    return pxt.packagesConfigAsync()
+                        .then(config => pxt.github.latestVersionAsync(ghConfig[1], config))
```
Comment (pelikhan) [inline pxtlib/main.ts]: not sure why we call lastestVersionAsync since we do not use ``tag`` afterwards

File: pxtlib/main.ts [hunk 3]
```diff
@@ -310,13 +348,84 @@ namespace pxt {
...
+                                ancestors.push.apply(allAncestors(a));
+                                ancestors.push(a);
+                            }
+                        });
+                        return ancestors;
+                    }
+                    const additionalConflicts: cpp.PkgConflictError[] = [];
+                    conflicts.forEach((c) => {
+                        additionalConflicts.push.apply(additionalConflicts, allAncestors(c.pkg0).map((anc) => {
+                            const confl = new cpp.PkgConflictError("");
```
Comment (pelikhan) [inline pxtlib/main.ts]: no details?

File: pxtlib/main.ts [hunk 4]
```diff
@@ -310,13 +348,84 @@ namespace pxt {
...
+                    conflicts = conflicts.filter((c, index) => {
+                        for (let i = 0; i < index; ++i) {
+                            if (c.pkg0.id === conflicts[i].pkg0.id) {
+                                return false;
+                            }
+                        }
+                        return true;
+                    });
+                })
+                .then(() => conflicts);
```
Comment (pelikhan) [inline pxtlib/main.ts]: when `.then(() `` here?

File: webapp/src/app.tsx [hunk 5]
```diff
@@ -260,14 +258,71 @@ class ScriptSearch extends data.Component<ISettingsProps, ScriptSearchState> {
...
+
+                    let addDependencyPromise = Promise.resolve(true);
+
+                    if (inUse) {
+                        addDependencyPromise = addDependencyPromise
+                            .then(() => core.confirmAsync({
+                                header: lf("Cannot add {0} package", config.name),
+                                hideCancel: true,
+                                agreeLbl: lf("Ok"),
+                                htmlBody: lf("Remove all the blocks from the {0} package and try again.", inUse.pkg0.id)
```
Comment (pelikhan) [inline webapp/src/app.tsx]: Use "body" instead.

**Comment by pelikhan** [comment]
image

Make it a single sentence: Packages ... are incompatiable with blah blah blah...

**Comment by pelikhan** [comment]
The simulator does not seem to restart after adding a package.

**Comment by pelikhan** [comment]
We should try to add end-to-end integration. Maybe you can add a CLI command that allows to add a package (eg "pxt install --save") so that we can automate test cases for the logic.
