### PR TITLE
Suggested fix for tutorial docs headings

### LINKED ISSUE #8670: Tutorials have curly braces
Hey Galen, can you look at this?
Seeing curly braces in the headings for the Tutorials
https://arcade.makecode.com/tutorials/happy-flower
image

### PR DESCRIPTION
**Pull request by ganicke**
The braces on the tutorial doc headings aren't removed when served from azure. I suspect there is a difference in the behavior of `string.trim()`. Here is a suggested fix for `render.heading` to address this. An additional change is in there to better form the header id's as well.

Fixes #8670

### CODE REVIEW

File: pxtlib/docsrender.ts [hunk 1]
```diff
@@ -437,16 +437,16 @@ namespace pxt.docs {
...
-                id = raw.toLowerCase().replace(/[^\w]+/g, '-')
             }
             // remove tutorial macros
             if (text)
                 text = text.replace(/@(fullscreen|unplugged|showdialog|showhint)/gi, '');
-            text = text.trim();
             // remove brackets for hiding step title
-            if (text.match(/^\{([\s\S]+)\}$/))
-                text = text.substr(1, text.length - 2);
+            if (text.match(/\{([\s\S]+)\}/))
```
Comment (shakao) [inline pxtlib/docsrender.ts:445]: hmm i think maybe something like 
```
if (text.match(/\{([\s\S]+)\}/)?.[1])
     text = text.match(/\{([\s\S]+)\}/)[1].trim()
```
would ensure that we're just getting the text between the brackets.... if someone has a title that's like `{TITLE} other text` it would only translate to `TITLE` but maybe that's okay? would result in a cleaner ID anyway

Comment (ganicke) [reply pxtlib/docsrender.ts:445]: Right, to make it simple, maybe just have the "rules" be that the heading is either all-visible or all-hidden. Heading text that breaks the rules will just need to get fixed when discovered. Go ahead and make the changes as you see fit. Thanks.

**Review by shakao — APPROVED** [review]

File: pxtlib/docsrender.ts (hunk 1 above)
Comment (shakao) [reply pxtlib/docsrender.ts:445]: cool, updated! (also great branch name hahaha)

Comment (ganicke) [reply pxtlib/docsrender.ts:445]: Thanks. BTW, this is the best regex I can come up with that discriminates something out of the first occurrence of "{blahblah123}".

`\{([^\{][\s\S]+?)\}`

yields: "Introduction " when the heading is crazy like:

`jjkkjk }}} {{Introduction }}{{ {more} or {less}`
