### PR TITLE
include special icons for the monaco flyout

### LINKED ISSUE #6754: Serial icon missing in Python/JavaScript editor
**Describe the bug**
When opening any project in the Python or JavaScript editor, Serial icon does not render correctly in the Serial and more two toolbox drawers.

**Steps to reproduce the behavior:**
1. Navigate to https://makecode.microbit.org/beta.
2. Create a new project or open an existing one.
3. Switch to the **JavaScript** or **Python** editor.
4. In the Toolbox, expand **Advanced**.
5. Click the **Serial** and adjacent **more** drawers.
6. Observe the icon rendering.

**Actual behavior**
The Serial icon isn't displayed in Python/JavaScript editor.
 
**Expected behavior**
The Serial icon should display correctly in the Python/JavaScript editor, consistent with the Blocks editor.

**Screenshots**
Image

**Additional context**
1.OS: Windows 11 25H2
2.Browser: Chrome, Edge, and Firefox
3.makecode.microbit.org version: 8.1.9
4.Microsoft MakeCode version: 12.3.3

### PR DESCRIPTION
**Pull request by srietkerk**
Fixes https://github.com/microsoft/pxt-microbit/issues/6754

### CODE REVIEW

File: webapp/src/monacoFlyout.tsx [hunk 1]
```diff
@@ -428,10 +434,11 @@ export class MonacoFlyout extends data.Component<MonacoFlyoutProps, MonacoFlyout
         const { name, ns, color, icon, groups, selectedBlock } = this.state;
         const rgb = pxt.toolbox.getAccessibleBackground(pxt.toolbox.convertColor(color || (ns && pxt.toolbox.getNamespaceColor(ns)) || "255"));
         const iconClass = `blocklyTreeIcon${icon ? (ns || icon).toLowerCase() : "Default"}`.replace(/\s/g, "");
+        const isBrandIcon = icon && icon in brandIcons;
```
Comment (jwunderl) [inline webapp/src/monacoFlyout.tsx]: teeny but `in` has some weird semantics / typically lean towards avoiding in favor of `.hasOwnProperty`. Almost certainly shouldn't impact anything in this case so feel free to ignore if don't feel like it~

Image

**Review by jwunderl — APPROVED** [review]
