### PR TITLE
Don't reload if already in the selected language

### LINKED ISSUE #4141: [Language dialog] Selecting "English" while already in English does a reload
This is a regression

### PR DESCRIPTION
**Pull request by guillaumejenkins**
Fixes #4141

### CODE REVIEW

File: pxtlib/util.ts [hunk 1]
```diff
@@ -737,7 +737,7 @@ namespace ts.pxtc.Util {
 
     }
 
-    function normalizeLanguageCode(code: string): string {
+    export function normalizeLanguageCode(code: string): string {
         if (!/^(es|pt|si|sv|zh)/i.test(code))
```
Comment (pelikhan) [inline pxtlib/util.ts]: we should revisit this...

Comment (guillaumejenkins) [reply pxtlib/util.ts]: Agreed that it's weird... Changed the normalization logic to instead ensure casing is consistent: `xx` and `xx-XX`
